### ISSUE TITLE
Notifications other than email

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry-incubator/notifications#15]
As a CF operator, in order to notify platform consumers of anything (but specifically important but short notifications like upcoming/ongoing platform upgrades), I'd like to be able to send notifications such that they could be rendered in a UI rather than via email.

Presumably this would be predicated on some UI client being able to receive / render notifications at all. I'm completely unaware if the Pivotal CF UI has an exposed endpoint to do this, if [stratos](https://github.com/cloudfoundry-incubator/stratos) has an ability to do this, etc...

... So I'm entirely talking out of my butt here. I imagine this would require many more moving parts than the notifications service. But I figured I'd put the idea out there.

This is just a spitball idea, so feel free to close this whenever. Thanks for your time 👍

**Comment by AllenDuet** [comment]
For UI representation an event model seems like a better approach for what you're suggesting.  Loggregator supports an event type and Log cache presents a REST like interface that seems like a better pattern for what you are suggesting.  

For things like state change those would be better represented as discreet events.  Are you asking about interpreting events from metrics (like a service warning if disk space is low)?  
Pivotal Event Alerts would be a better product for converting metrics to events and providing it out for visual representation.

**Comment by aegershman** [comment]
Honestly I was poorly articulating a desire to send notifications that would appear as something like a modal in an application-manager UI.

Unfortunately I don't think I did a great job of expressing that, nor is this really the best place for it.

I'll go ahead and close this out. Thanks for your response and your time!
