### ISSUE TITLE
Evan should edit this

### ISSUE THREAD

**Issue by supertopher** [cloudfoundry-incubator/notifications#5]
The readme for APIs V2 has a comment that `EVAN WILL EDIT THIS` just trying to fulfill the prophesy 

[here](https://github.com/cloudfoundry-incubator/notifications/blob/master/V2_API.md#L18)

**Comment by ryanmoran** [comment]
We put those into the docs at a point when the PM of the team (Evan) was going to be able to fill in descriptions for each of the API endpoints. Sadly, the team was completely disbanded very shortly after that was done. Evan is no longer a PM, he transferred back to engineering. And he certainly in not the PM of the notifications service anymore. At this moment there is no team maintaining this project. But there is hope for the future. Next week I will be visiting the Pivotal Toronto office to help handoff this project to a team located in that office. I will keep this issue open, and hopefully at some time in that week we may be able to tackle some of this documentation debt.

**Comment by iplay88keys** [comment]
Closing since the V2 api was removed and this is no longer relevant.
